---
title: "資料視覺化作品集"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    css: null
    js: null
    includes:
      in_header: ["external_dd/in_header/in_header.html"]
      before_body: ["external_dd/before_body/before_body.html"]
      after_body: ["external_dd/after_body/after_body.html"]
params:
  output_filename: "display_flex.html"
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r local serve, eval=F, echo=F}
servr::daemon_stop(
  which=servr::daemon_list()
)
servr::httd(dir=".",port=8000,initpath=params$output_filename)
```





Inputs {.sidebar data-width=200}
-------------------------------------

<div id="sidebar_hD" width="100%" height="100%"></div>
<script type="text/javascript" src="https://pym.nprapps.org/pym.v1.min.js"></script>
<script>
    var pymParent = new pym.Parent("sidebar_hD", "sidebar_hDisplay.html", {});
</script>



Column {data-width=550}
-----------------------------------------------------------------------

### 圖片展示

<object id="hw1" data="svg/hw1.svg" type="image/svg+xml" width="100%" style="display: block">
</object>

<object id="hw2" data="svg/hw2.svg" type="image/svg+xml" width="100%" style="display: none">
</object>

<object id="hw3" data="svg/hw3.svg" type="image/svg+xml" width="100%" style="display: none">
</object>

<object id="hw4" data="svg/hw4.svg" type="image/svg+xml" width="100%" style="display: none">
</object>

<object id="hw5" data="svg/hw5.svg" type="image/svg+xml" width="100%" style="display: none">
</object>

<object id="hw6" data="svg/hw6.svg" type="image/svg+xml" width="100%" style="display: none">
</object>



Column {data-width=250}
-----------------------------------------------------------------------

### 圖片說明

```{r}

htmltools::includeHTML(path = "external_dd/explainPlot.html")

```


### 設計理念

<p>
  利用顏色的深淺，來強調六都性別觀念的開放程度，愈深代表性別觀念愈開放。
</p>
